version: '3.8'

services:
  upvrt:
    build: .
    container_name: upvrt
    restart: unless-stopped
    ports:
      - "7001:7001"
    command: python -u -m gunicorn --bind 0.0.0.0:7001 --access-logfile=- --error-logfile=- --log-level=info --capture-output wsgi:app
    volumes:
      - ./uploads:/app/uploads
      - ./assets:/app/assets
      - ./static:/app/static
    env_file:
      - .env 